// Mock "My Rides" data — used only when signed in via the client-only local dev sign-in
// (AuthContext's signInAsLocalDevUser), which has no real server behind it at all. Without
// this, My Rides (and the home screen's Track tab, which is just My Rides filtered to
// finished) stays empty forever in that mode, which reads as a bug rather than the expected
// "there's no real backend for this fake session" — see eventsStore.ts's loadMyRides.
//
// Real accounts never see this: it's only reached when the real API call fails AND nothing
// is cached AND the access token is the local-dev-fake sentinel.

import type { EventSummary } from "./local-db";

// Distance/climb aren't hand-repeated on all 13 entries below — applied by index via the
// map() at the bottom, same pattern as mock-tracks.ts's LIKES_BY_INDEX.
const DISTANCE_KM_BY_INDEX = [62, 41, 102, 38, 55, 48, 158, 68, 25, 95, 22, 40, 30];
const CLIMB_M_BY_INDEX = [820, 1120, 1540, 60, 980, 540, 2100, 900, 300, 1350, 40, 320, 250];

const RAW_MY_RIDES: Omit<EventSummary, "distanceKm" | "climbM">[] = [
  {
    id: "mock-my-1",
    code: "SUN-742",
    name: "Sunday Morning Ride",
    type: "RIDE",
    status: "registration_open",
    visibility: "public",
    displayMode: "standard",
    startsAt: "2026-08-16T05:00:00.000Z",
    endsAt: null,
    location: "Galilee, Israel",
    ownerId: -1,
  },
  {
    id: "mock-my-2",
    code: "HIL-100",
    name: "Weekly Hill Climb",
    type: "RACE",
    status: "ready",
    visibility: "public",
    displayMode: "competition",
    startsAt: "2026-08-20T04:30:00.000Z",
    endsAt: null,
    location: "Jerusalem Hills, Israel",
    ownerId: -1,
  },
  {
    id: "mock-my-3",
    code: "GRV-245",
    name: "Spring Gravel Classic",
    type: "RACE",
    status: "finished",
    visibility: "public",
    displayMode: "competition",
    startsAt: "2026-04-12T04:00:00.000Z",
    endsAt: "2026-04-12T09:00:00.000Z",
    location: "Negev, Israel",
    ownerId: -1,
  },
  {
    id: "mock-my-4",
    code: "CST-312",
    name: "Coastal Sunset Ride",
    type: "RIDE",
    status: "finished",
    visibility: "public",
    displayMode: "standard",
    startsAt: "2026-03-06T15:00:00.000Z",
    endsAt: "2026-03-06T17:30:00.000Z",
    location: "Tel Aviv, Israel",
    ownerId: -1,
  },
  {
    id: "mock-my-5",
    code: "WNT-201",
    name: "Winter Hill Repeats",
    type: "RIDE",
    status: "finished",
    visibility: "private",
    displayMode: "standard",
    startsAt: "2026-01-24T05:30:00.000Z",
    endsAt: "2026-01-24T08:00:00.000Z",
    location: "Jerusalem Hills, Israel",
    ownerId: -1,
  },
  {
    id: "mock-my-6",
    code: "NYD-305",
    name: "New Year's Day Loop",
    type: "RIDE",
    status: "finished",
    visibility: "public",
    displayMode: "standard",
    startsAt: "2026-01-01T05:00:00.000Z",
    endsAt: "2026-01-01T08:00:00.000Z",
    location: "Galilee, Israel",
    ownerId: -1,
  },
  {
    id: "mock-my-7",
    code: "AUT-390",
    name: "Autumn Century Ride",
    type: "RIDE",
    status: "finished",
    visibility: "public",
    displayMode: "standard",
    startsAt: "2025-11-14T04:30:00.000Z",
    endsAt: "2025-11-14T10:00:00.000Z",
    location: "Sharon, Israel",
    ownerId: -1,
  },
  {
    id: "mock-my-8",
    code: "DES-411",
    name: "Desert Gravel Grinder",
    type: "RACE",
    status: "finished",
    visibility: "public",
    displayMode: "competition",
    startsAt: "2025-10-03T04:00:00.000Z",
    endsAt: "2025-10-03T09:30:00.000Z",
    location: "Negev, Israel",
    ownerId: -1,
  },
  {
    id: "mock-my-9",
    code: "MTB-021",
    name: "Midweek MTB Session",
    type: "RIDE",
    status: "draft",
    visibility: "private",
    displayMode: "standard",
    startsAt: "2026-08-27T15:30:00.000Z",
    endsAt: null,
    location: "Jerusalem Hills, Israel",
    ownerId: -1,
  },
  {
    id: "mock-my-10",
    code: "CLB-088",
    name: "Club Championship",
    type: "RACE",
    status: "published",
    visibility: "public",
    displayMode: "competition",
    startsAt: "2026-09-05T04:30:00.000Z",
    endsAt: null,
    location: "Negev, Israel",
    ownerId: -1,
  },
  {
    id: "mock-my-11",
    code: "BCH-109",
    name: "Beach Cruiser Meetup",
    type: "RIDE",
    status: "registration_open",
    visibility: "public",
    displayMode: "standard",
    startsAt: "2026-08-23T15:00:00.000Z",
    endsAt: null,
    location: "Tel Aviv, Israel",
    ownerId: -1,
  },
  {
    id: "mock-my-12",
    code: "TTL-144",
    name: "Sunrise Time Trial",
    type: "RACE",
    status: "cancelled",
    visibility: "public",
    displayMode: "competition",
    startsAt: "2026-08-30T04:00:00.000Z",
    endsAt: null,
    location: "Sharon, Israel",
    ownerId: -1,
  },
  {
    id: "mock-my-13",
    code: "LIV-177",
    name: "Live Now — Group Ride",
    type: "RIDE",
    status: "live",
    visibility: "public",
    displayMode: "standard",
    startsAt: "2026-08-14T05:00:00.000Z",
    endsAt: null,
    location: "Galilee, Israel",
    ownerId: -1,
  },
];

export const MOCK_MY_RIDES: EventSummary[] = RAW_MY_RIDES.map((ride, i) => ({
  ...ride,
  distanceKm: DISTANCE_KM_BY_INDEX[i % DISTANCE_KM_BY_INDEX.length],
  climbM: CLIMB_M_BY_INDEX[i % CLIMB_M_BY_INDEX.length],
}));
