// Mock "Find Rides" data — same story as mock-my-rides.ts: only ever reached when the real
// `/events/public` call fails AND nothing is cached AND this session signed in via the
// client-only local dev sign-in (no real server behind it at all). Without this, Find Rides
// stays empty forever in that mode, same "reads as a bug, not the expected no-backend state"
// problem mock-my-rides.ts exists to avoid — see eventsStore.ts's loadOtherRides.
//
// ownerId is a distinct, made-up id per row (never -1, the local dev user's own id — see
// AuthContext.signInAsLocalDevUser) so these always read as genuinely other people's rides,
// never this rider's own.

import type { EventSummary } from "./local-db";

const RAW_OTHER_RIDES: EventSummary[] = [
  {
    id: "mock-other-1",
    code: "SAT-501",
    name: "Saturday Jerusalem Hills Loop",
    type: "RIDE",
    status: "registration_open",
    visibility: "public",
    displayMode: "standard",
    startsAt: "2026-08-16T05:00:00.000Z",
    endsAt: null,
    location: "Jerusalem, Israel",
    ownerId: 2001,
  },
  {
    id: "mock-other-2",
    code: "GLC-118",
    name: "Golan Climbers Gathering",
    type: "RIDE",
    status: "live",
    visibility: "public",
    displayMode: "standard",
    startsAt: "2026-08-14T05:00:00.000Z",
    endsAt: null,
    location: "Golan Heights, Israel",
    ownerId: 2002,
  },
  {
    id: "mock-other-3",
    code: "NGV-330",
    name: "Negev Night Gravel",
    type: "RIDE",
    status: "registration_open",
    visibility: "public",
    displayMode: "standard",
    startsAt: "2026-08-21T16:00:00.000Z",
    endsAt: null,
    location: "Negev, Israel",
    ownerId: 2003,
  },
  {
    id: "mock-other-4",
    code: "SHR-072",
    name: "Sharon Easy Sunday Spin",
    type: "RIDE",
    status: "published",
    visibility: "public",
    displayMode: "standard",
    startsAt: "2026-08-23T04:30:00.000Z",
    endsAt: null,
    location: "Sharon, Israel",
    ownerId: 2004,
  },
  {
    id: "mock-other-5",
    code: "CRM-266",
    name: "Carmel Forest MTB Meetup",
    type: "RIDE",
    status: "registration_open",
    visibility: "public",
    displayMode: "standard",
    startsAt: "2026-08-19T14:30:00.000Z",
    endsAt: null,
    location: "Haifa, Israel",
    ownerId: 2005,
  },
  {
    id: "mock-other-6",
    code: "ARV-410",
    name: "Arava Sunrise Century",
    type: "RIDE",
    status: "published",
    visibility: "public",
    displayMode: "standard",
    startsAt: "2026-09-04T03:30:00.000Z",
    endsAt: null,
    location: "Arava, Israel",
    ownerId: 2006,
  },
  {
    id: "mock-other-7",
    code: "TLV-088",
    name: "Tel Aviv Boardwalk Cruise",
    type: "RIDE",
    status: "finished",
    visibility: "public",
    displayMode: "standard",
    startsAt: "2026-07-18T15:00:00.000Z",
    endsAt: "2026-07-18T17:00:00.000Z",
    location: "Tel Aviv, Israel",
    ownerId: 2007,
  },
  {
    id: "mock-other-8",
    code: "GAL-905",
    name: "Galilee Gravel Grinders",
    type: "RIDE",
    status: "finished",
    visibility: "public",
    displayMode: "standard",
    startsAt: "2026-06-27T04:00:00.000Z",
    endsAt: "2026-06-27T09:00:00.000Z",
    location: "Galilee, Israel",
    ownerId: 2008,
  },
];

export const MOCK_OTHER_RIDES: EventSummary[] = RAW_OTHER_RIDES;
